### ISSUE TITLE
Use python2 Shebang

### ISSUE THREAD

**Issue by hashworks** [clinton-hall/GetScripts#12]
Shebang `#!/usr/bin/env python` results in Python 3 being used on my system. I suggest `#!/usr/bin/env python2`.

**Comment by clinton-hall** [comment]
or I try and make these scripts python 3  compatible...

**Comment by hashworks** [comment]
Then I would still recommend the `#!/usr/bin/env python3` shebang in case the distro has set python2 as default. Also, never change a running system, if you're comfortable with python 2 go with it

**Comment by clinton-hall** [comment]
the intention would be to make this stable under python2 and python3 in the hopes that `python` would work.

In nzbToMedia I ran into big issues with `python2` as this doesn't work on OSX... As a result I have a default branch using `python2` and an OSX branch using `python`

**Comment by clinton-hall** [comment]
Created a new branch. to use
```
git pull
git checkout python2
```
