### ISSUE TITLE
SafeRename quits with Errno2

### ISSUE THREAD

**Issue by Pixelfanatic** [clinton-hall/GetScripts#13]
Unfortunately I get the following error when using SafeRename with Sabnzbd:

> Script triggered from SABnzbd
> [INFO] Extracting file /share/Downloads/complete/tv/xxxx/win_click2rename.bat with command UnRAR.exe x -p339124433 Click.rar
> Traceback (most recent call last):
>   File "/usr/share/sabnzbdplus/sabnzbd/SafeRename.py", line 160, in <module>
>     rename_script(dirname)
>   File "/usr/share/sabnzbdplus/sabnzbd/SafeRename.py", line 117, in rename_script
>     p = Popen(cmd, stdout=devnull, stderr=devnull)  # should extract files fine.
>   File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Edit: 
(Reason: Tried NZBget - same error)

> ERROR	Sat Aug 13 2016 10:57:51	Post-process-script SafeRename.py for xxxxx failed (terminated with unknown status)
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: OSError: [Errno 2] No such file or directory
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: raise child_exception
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: errread, errwrite)
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: p = Popen(cmd, stdout=devnull, stderr=devnull) # should extract files fine.
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: File "/opt/nzbget/scripts/SafeRename.py", line 117, in rename_script
> INFO	Sat Aug 13 2016 10:57:51	SafeRename: rename_script(dirname)

**Comment by clinton-hall** [comment]
Sorry for the delay here... missed this issue.

Looks like you are on Linux and the script is find a Windows UnRar command.
So I'll need to add some logic to convert this to a Linux usable unrar or 7zip extraction.

**Comment by clinton-hall** [comment]
Please update and test. Hopefully this works now.
