### ISSUE TITLE
[Feature request] flatten script unpack recursively

### ISSUE THREAD

**Issue by ajkis** [clinton-hall/GetScripts#15]
I would like to thank you for great nzbget scripts here and would ask for an upgrade of flatten script.
A lot of downloaded files come with subtitles that are rared inside original rar.
Is it possible for your flatten script to check for those and unrar them as well.

**Comment by clinton-hall** [comment]
Since NZBGet allows you to run multiple scripts, if you run 
1. passwordlist.py (to extract any archives)
2. flatten.py
this should achieve the same?

**Comment by ajkis** [comment]
Interesting, I never used it, so passwordlist.py will extract the ones without pass as well.

**Comment by TRaSH-** [comment]
i'm testing this for someone,
but it isn't unpacking the rar files in the rar container.
