### ISSUE TITLE
Problem with /usr/bin/env python on freenas 11

### ISSUE THREAD

**Issue by philsynek** [clinton-hall/GetScripts#17]
Hi Clinton,

thanks for the great work! Unfortunately I am running into problems with the scripts. I use SafeRename and DeleteSamples. When I try to postprocess them they log the error:

> SafeRename: env: python: No such file or directory

My env is: `PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin`

`ls -l /usr/local/bin | grep python`:

lrwxr-xr-x    1 root  wheel        7 Jun 29 03:24 python -> python2
lrwxr-xr-x    1 root  wheel       14 Jun 29 03:24 python-config -> python2-config
lrwxr-xr-x    1 root  wheel        9 Jun 29 03:19 python2 -> python2.7
lrwxr-xr-x    1 root  wheel       16 Jun 29 03:19 python2-config -> python2.7-config
-r-xr-xr-x    1 root  wheel     5432 Jun 29 03:18 python2.7
-r-xr-xr-x    1 root  wheel     1769 Jun 29 03:18 python2.7-config

I tried to change the shebang to `#!/usr/local/bin/python`, but then the script had problems to find the unpack commands further down the script. I didn't want to change every single appearance of these commands.

Any suggestions?
Thx,
Phil

**Comment by clinton-hall** [comment]
> but then the script had problems to find the unpack commands further down the script.

can you show the log/output when the script runs but fails to unpack?

**Comment by philsynek** [comment]
Hi Clinton,
sure:

> Sat Jul 29 04:10:02 2017        INFO    Executing post-process-script GetScripts/DeleteSamples.py for Happy.Feet.2006.German.DL.720p.BluRay.x264.iNTERNAL-1aQuali
Sat Jul 29 04:10:02 2017        INFO    DeleteSamples: Script triggered from NZBGet Version 19.0.
Sat Jul 29 04:10:02 2017        INFO    Post-process-script GetScripts/DeleteSamples.py for Happy.Feet.2006.German.DL.720p.BluRay.x264.iNTERNAL-1aQuali successful
Sat Jul 29 04:10:02 2017        INFO    Executing post-process-script GetScripts/SafeRename.py for Happy.Feet.2006.German.DL.720p.BluRay.x264.iNTERNAL-1aQuali
Sat Jul 29 04:10:02 2017        INFO    SafeRename: Script triggered from NZBGet Version 19.0.
Sat Jul 29 04:10:02 2017        INFO    SafeRename: unrar not found, disabling support for .rar
Sat Jul 29 04:10:02 2017        INFO    SafeRename: 7zr not found, disabling support for .7z
Sat Jul 29 04:10:02 2017        INFO    SafeRename: Traceback (most recent call last):
Sat Jul 29 04:10:02 2017        INFO    SafeRename:   File "/media/downloads/nzbget/scripts/GetScripts/SafeRename.py", line 264, in <module>
Sat Jul 29 04:10:02 2017        INFO    SafeRename:     rename_script(dirname)
Sat Jul 29 04:10:02 2017        INFO    SafeRename:   File "/media/downloads/nzbget/scripts/GetScripts/SafeRename.py", line 130, in rename_script
Sat Jul 29 04:10:02 2017        INFO    SafeRename:     cmd = extract_command(shlex.split(line), dirname)
Sat Jul 29 04:10:02 2017        INFO    SafeRename:   File "/media/downloads/nzbget/scripts/GetScripts/SafeRename.py", line 259, in extract_command
Sat Jul 29 04:10:02 2017        INFO    SafeRename:     newcmd = EXTRACT_COMMANDS[ext]
Sat Jul 29 04:10:02 2017        INFO    SafeRename: KeyError: '.rar'
Sat Jul 29 04:10:02 2017        ERROR   Post-process-script GetScripts/SafeRename.py for Happy.Feet.2006.German.DL.720p.BluRay.x264.iNTERNAL-1aQuali failed (terminated with unknown status)

Additionally I changed the following lines and the script works:

> required_cmds = ["/usr/local/bin/unrar", "unzip", "tar", "unxz", "unlzma", "7zr", "bunzip2"]
        EXTRACT_COMMANDS = {
            ".rar": ["/usr/local/bin/unrar", "x", "-o+", "-y"],

Thanks and regards,
Phil
