### ISSUE TITLE
Delete Sample failing

### ISSUE THREAD

**Issue by edasque** [clinton-hall/GetScripts#18]
Hi,

using NZBGet, I see the follow PP error:
```Post-process-script GetScripts/DeleteSamples.py for _nzb_name_ failed (terminated with unknown status)```

Is there a way for me to give you more diagnostics data?

```
python --version
Python 2.7.12
```

**Comment by clinton-hall** [comment]
If you enable all logging options in NZBGet, does this show anything else prior to the error above?

**Comment by edasque** [comment]
Yeah, I think that was the issue. It'd be good to have a more descriptive error from DeleteSample though.
