### ISSUE TITLE
searching the .sh / .bat script: suggestions

### ISSUE THREAD

**Issue by sanderjo** [clinton-hall/GetScripts#4]
Minor / cosmetic thing:

Current code:
```
if re.search('(rename\S*\.(sh|bat))',file):
```
will also find rename.sh.old. It will not find rename.BAT

I changed it to:
```
if re.search('(rename\S*\.(sh|bat)$)',file,re.IGNORECASE):
```

HTH

**Comment by clinton-hall** [comment]
Thanks for this. I have also made this change in my main nzbToMedia project...
Now to get my head around your other fix.
