### ISSUE TITLE
Handle rared rename.sh file

### ISSUE THREAD

**Issue by w00druff** [clinton-hall/GetScripts#6]
Some boards are packing the rename.sh file now-
within a password protected rar archive named What.rar

There is a „a_Linux_2rename.sh“ file in main dir now containing this:
unrar x -p73522169 What.rar 
./What.sh

Now that What.sh file is our rename script containing our known move commands.

**Comment by clinton-hall** [comment]
ok... give this ago...

I don't know what will happen if they change the naming convention from what you have described...

**Comment by w00druff** [comment]
Thanks, but it doesnt work ...
p = Popen(cmd2, stdout=devnull, stderr=devnull)  # should extract files fine.
cmd2 is not defined, tried it with cmd, then it tells me that he is extracting the rename.sh file but nothing happens.

**Comment by clinton-hall** [comment]
hmmm.. try this last one..

**Comment by w00druff** [comment]
Thanks, extracting works now, but then i get this.
[INFO] Extraction was successfull
Traceback (most recent call last):
  File "/home/sabnzbd/.sabnzbd/scripts/SafeRename.py", line 147, in <module>
    rename_script(dirname)
  File "/home/sabnzbd/.sabnzbd/scripts/SafeRename.py", line 127, in rename_script
    newfile = os.path.splitext(cmd[-1])[0] + '.sh'
IndexError: list index out of range

**Comment by clinton-hall** [comment]
ok... sorry for that. I reset the cmd before trying ti build the new file name.
This last one should get closer...

**Comment by w00druff** [comment]
No problem, thank you !
I think we get a bit closer to the goal :)
Now i get "extraction successfull" but no renamings done.

Just to check, this is the content of my tested What.sh file:
#!/bin/bash
mkdir Testdir
mv    05.02.2015.1 Test1/test.nfo
mv    05.02.2015.2 Test1/testmovie.mkv
mv    05.02.2015.3   Test1/Subs
mv    Test1/Subs/05.02.2015.4  Test1/Subs/test.sub
mv    Test1/Subs/05.02.2015.5  Test1/Subs/test.idx

**Comment by clinton-hall** [comment]
ok... can you test this?

**Comment by w00druff** [comment]
Same result, extraction successfull but nothing further ...
It is slowly getting me uncomfortable because of your time :(
What about just running that What.sh file if there just mv/move/mkdir commands in THIS dir ?

**Comment by clinton-hall** [comment]
ok, can you try again.
This won't work yet, but it should add new logging that will help show where this goes wrong.

I'm expecting it is looking for the wrong file, but I can't see why right now.

**Comment by clinton-hall** [comment]
and don't be uncomfortable about this... This is my project and I only spend what time I can...

**Comment by w00druff** [comment]
[INFO] Extracting file /media/ed602aaf-dacf-4178-bca6-d6652f1d95d6/DATA/_DOWNLOAD/532ff4ee_0f5c1c3c_9b29df68_bf88dcd-u4e/532ff4ee_0f5c1c3c_9b29df68_bf88dcd/a_Linux_2rename.sh with command unrar x -p2540117263 What.rar
[INFO] Extraction was successfull
[INFO] Checking for file /media/ed602aaf-dacf-4178-bca6-d6652f1d95d6/DATA/_DOWNLOAD/532ff4ee_0f5c1c3c_9b29df68_bf88dcd-u4e/532ff4ee_0f5c1c3c_9b29df68_bf88dcd/What.sh
[INFO] Reading lines from /media/ed602aaf-dacf-4178-bca6-d6652f1d95d6/DATA/_DOWNLOAD/532ff4ee_0f5c1c3c_9b29df68_bf88dcd-u4e/532ff4ee_0f5c1c3c_9b29df68_bf88dcd/What.sh

**Comment by clinton-hall** [comment]
sorry for the delay here... but this project does come second to life :)
I recon I found the issue. This should hopefully make this work, but in any case I have increased the logging (for now) to try and see where it falls over if it doesn't work.

**Comment by w00druff** [comment]
I can check in ~2hours, thanks mate :)

**Comment by w00druff** [comment]
Ill post log after parsing and i can see the problem.
In our What.sh file is a mkdir command ... he wants to make the dir DIRXXXXXXX.
So renaming doesnt work because of the missing dir i think ?

[INFO] Renaming file /media/ed602aaf-dacf-4178-bca6-d6652f1d95d6/DATA/_DOWNLOAD/532ff4ee_0f5c1c3c_9b29df68_bf88dcd-u4e/532ff4ee_0f5c1c3c_9b29df68_bf88dcd/05.02.2015.1 to /media/ed602aaf-dacf-4178-bca6-d6652f1d95d6/DATA/_DOWNLOAD/532ff4ee_0f5c1c3c_9b29df68_bf88dcd-u4e/532ff4ee_0f5c1c3c_9b29df68_bf88dcd/DIRXXXXXXX/xxxxxxx.nfo
[ERROR] Unable to rename file due to: [Errno 2] No such file or directory

**Comment by clinton-hall** [comment]
ok... added the mkdir command... can't believe I missed that!

**Comment by w00druff** [comment]
Okay mkdir worked and nearly all files got renamed :)

Here the What.sh file with notes what worked:
#!/bin/bash
mkdir Test CHECK !
mv    05.02.2015.1 Test/test.nfo CHECK !
mv    05.02.2015.2 Test/Test.mkv CHECK !
mv    05.02.2015.3   Test/Subs NOPE !
mv    Test/Subs/05.02.2015.4  Test/Subs/Test.sub NOPE !
mv    Test/Subs/05.02.2015.5  Test/Subs/Test.idx NOPE !

Maybe because there are two spaces in the mv command ?

**Comment by clinton-hall** [comment]
the problem was it only renamed files, not directories... this should work now

**Comment by clinton-hall** [comment]
sorry for the lengthy process here...

**Comment by w00druff** [comment]
Okay i can try in few hours, thanks !
You do not have to apologize, I appreciate your time !!!

**Comment by w00druff** [comment]
Okay mate, works very good, thanks a lot !
Last question, is it possible for you to chmod 775 all files and dirs after successfull rename ?
And maybe also a cleanup of all .sh, .rar, .zip, .bat files ? :)

**Comment by clinton-hall** [comment]
Finally added...
