### ISSUE TITLE
SafeRename mkdir

### ISSUE THREAD

**Issue by joshuader6** [clinton-hall/GetScripts#9]
Hello, 
Lately i've been getting a lot of rename.sh files like this: 

```sh
#!/bin/bash
mkdir Marvels.Agents.of.S.H.I.E.L.D.S01E03.The.Asset.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP
mv    02.07.2014.1 Marvels.Agents.of.S.H.I.E.L.D.S01E03.The.Asset.GERMAN.DL.DUBBED.1080p.WebHD.x264-TVP/tvp-shield-s01e03-1080p.mkv
```

Is there any way we could execute the mkdir command to? Or even better ignore it and remove it's folder from the mv string? 

Greetings 
Josh

**Comment by w00druff** [comment]
Would be great !

**Comment by w00druff** [comment]
Thanks !!!
